// The demo site's pages, served to real browsers by the seed and to the
// heatmap overlay by the tour.
const products = [
  { id: "seed-starter-kit", name: "Seed starter kit", category: "Kits", price: 3800, weight: 34 },
  { id: "terracotta-planter", name: "Terracotta planter, 30 cm", category: "Planters", price: 3500, weight: 22 },
  { id: "urban-garden-guide", name: "Urban garden guide (PDF)", category: "Guides", price: 900, weight: 24 },
  { id: "balcony-worm-bin", name: "Balcony worm bin", category: "Compost", price: 6900, weight: 9 },
  { id: "workshop-seed-saving", name: "Workshop: seed saving", category: "Workshops", price: 4500, weight: 11 },
];
const guides = [["/guides/urban-gardens", 30], ["/guides/balcony-tomatoes", 26], ["/guides/composting-small-spaces", 15], ["/guides/herbs-in-shade", 12], ["/guides/watering-while-away", 9]];
const journal = ["/journal/the-balcony-that-feeds-us", "/journal/slow-weekends", "/journal/seed-swap-diary", "/journal/first-frost"];
export function pages(snippet) {
  const style = `body{margin:0;font:17px/1.6 Georgia,serif;color:#24302a;background:#fbfaf6}header{display:flex;gap:22px;align-items:center;padding:18px 32px;border-bottom:1px solid #e7e3d8;background:#fff}header b{font:600 20px Georgia;margin-right:auto;color:#2f6b45}header a{color:#24302a;text-decoration:none;font:15px system-ui}main{max-width:820px;margin:0 auto;padding:32px}h1{font-size:40px;line-height:1.15;margin:12px 0}.hero{background:linear-gradient(135deg,#dbe9d6,#f3ead7);border-radius:18px;padding:40px;margin-bottom:28px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.card{display:block;background:#fff;border:1px solid #e7e3d8;border-radius:14px;padding:18px;color:inherit;text-decoration:none}.card i{display:block;height:120px;border-radius:10px;margin-bottom:10px;background:linear-gradient(135deg,#b9d3b0,#e6d3b3)}button,.button{font:600 15px system-ui;padding:12px 20px;border-radius:10px;border:0;background:#2f6b45;color:#fff;cursor:pointer;display:inline-block;text-decoration:none}button.quiet{background:#fff;color:#24302a;border:1px solid #cfc9b8}form{display:grid;gap:10px;max-width:440px}input{font:16px system-ui;padding:11px;border:1px solid #cfc9b8;border-radius:8px}footer{padding:40px 32px;color:#7a776c;font:14px system-ui;border-top:1px solid #e7e3d8;margin-top:60px}p.lead{font-size:20px;color:#4b5a51}`;
  const layout = (title, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · Field Notes</title>${snippet}<style>${style}</style></head><body><header><b>Field Notes</b><a href="/guides/urban-gardens">Guides</a><a href="/journal/the-balcony-that-feeds-us">Journal</a><a href="/shop">Shop</a><a href="/workshops">Workshops</a><a href="https://instagram.com/fieldnotes" class="ext">Instagram</a></header><main>${body}</main><footer>Field Notes · balcony gardening since 2019 · <a href="/newsletter">Newsletter</a> · <a href="/about">About</a></footer></body></html>`;
  const prose = (n) => Array.from({ length: n }, (_, index) => `<p>${["Start with light: six hours of sun grows tomatoes, four grows herbs, and anything less still grows lettuce.", "Soil matters more than pots. A 30 litre container holds water through a hot weekend; a 10 litre one does not.", "Water in the morning, deeply, and let the top two centimetres dry before the next round.", "Feed every two weeks once the first flowers open, and pinch side shoots so the plant puts its effort into fruit."][index % 4]}</p>`).join("");
  const fixture = {
    "/": layout("Home", `<div class="hero" data-analytics-section="hero"><h1>Grow food on a balcony</h1><p class="lead">Seasonal guides, seeds and workshops for small city gardens.</p><a class="button" href="/guides/urban-gardens">Start with the basics</a></div><div class="grid" data-analytics-section="latest"><a class="card" href="/guides/balcony-tomatoes"><i></i>Balcony tomatoes</a><a class="card" href="/shop/seed-starter-kit"><i></i>Seed starter kit</a><a class="card" href="/journal/the-balcony-that-feeds-us"><i></i>The balcony that feeds us</a><a class="card" href="/workshops"><i></i>Workshops</a></div><p data-analytics-section="newsletter-cta">Join 4,000 readers. <a href="/newsletter">Get the newsletter</a></p>`),
    "/shop": layout("Shop", `<h1>Shop</h1><form action="/search"><input name="q" placeholder="Search the shop" aria-label="Search"><button>Search</button></form><br><div class="grid" data-analytics-section="products">${products.map((product) => `<a class="card" href="/shop/${product.id}"><i></i>${product.name}<br><small>€${(product.price / 100).toFixed(2)}</small></a>`).join("")}</div>`),
    "/search": layout("Search", `<h1>Search results</h1><div data-analytics-search-results="3"><a class="card" href="/shop/seed-starter-kit">Seed starter kit</a></div>`),
    "/workshops": layout("Workshops", `<h1>Workshops</h1><div class="grid" data-analytics-section="dates"><div class="card"><h2>Balcony basics</h2><p>Saturday 18 October</p><button id="basics" class="quiet">Details</button></div><div class="card"><h2>Seed saving</h2><p>Sunday 26 October</p><a class="button" data-analytics-action="book" href="/shop/workshop-seed-saving">Book a place</a></div></div>`),
    "/checkout": layout("Checkout", `<h1>Checkout</h1><form name="checkout" onsubmit="event.preventDefault()"><input name="email" type="email" required placeholder="Email" aria-label="Email"><input name="address" placeholder="Street and number" aria-label="Address"><input name="postcode" placeholder="Postcode" pattern="[0-9]{5}" aria-label="Postcode"><button id="pay">Pay now</button></form>`),
    "/newsletter": layout("Newsletter", `<h1>The Thursday letter</h1><p class="lead">One short email a week: what to sow, what to harvest, what went wrong.</p><form name="newsletter" onsubmit="event.preventDefault();analytico.track('newsletter_signup',{placement:'page'})"><input name="email" type="email" required placeholder="you@example.com" aria-label="Email"><button>Subscribe</button></form>`),
    "/about": layout("About", `<h1>About</h1>${prose(3)}`),
  };
  for (const [path] of guides) fixture[path] = layout("Guide", `<h1 data-analytics-section="intro">${path.split("/").pop().replaceAll("-", " ")}</h1><p class="lead">A practical guide for small spaces.</p><div data-analytics-section="materials">${prose(4)}</div><div data-analytics-section="steps">${prose(10)}<a href="/files/planting-calendar.pdf">Planting calendar (PDF)</a></div><p data-analytics-section="newsletter-cta"><a class="button" href="/newsletter">Get the Thursday letter</a></p>`);
  for (const path of journal) fixture[path] = layout("Journal", `<h1 data-analytics-section="story">${path.split("/").pop().replaceAll("-", " ")}</h1>${prose(14)}<div data-analytics-section="photos" class="grid"><a class="card"><i></i></a><a class="card"><i></i></a></div>`);
  for (const product of products) fixture[`/shop/${product.id}`] = layout(product.name, `<div data-analytics-section="gallery" class="card"><i style="height:260px"></i></div><h1>${product.name}</h1><p class="lead">€${(product.price / 100).toFixed(2)}</p><div data-analytics-section="details">${prose(2)}</div><button data-analytics-action="add-to-cart" onclick="analytico.track('add_to_cart',{},{value_minor:${product.price},currency:'EUR',items:[{id:'${product.id}',name:'${product.name}',category:'${product.category}',price_minor:${product.price},quantity:1}]});location.href='/checkout'">Add to cart</button><div data-analytics-section="reviews">${prose(2)}</div>`);
  return fixture;
}
