//! Build step: cuts the six tracker variants out of assets/tracker-source.js,
//! assembles the replay recorder and heatmap overlay, and writes hashes.zig
//! with each script's content hash. Run by build.zig; the output lives in the
//! build cache, never in the repository.
//!
//! gen_trackers <tracker-source.js> <replay-recorder.js> <overlay.js> <rrweb-record.min.js> <out-dir>
const std = @import("std");

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 6) return error.Usage;
    const cwd = std.Io.Dir.cwd();
    const read = struct {
        fn file(a: std.mem.Allocator, i: std.Io, path: []const u8) ![]const u8 {
            return std.Io.Dir.cwd().readFileAlloc(i, path, a, .limited(4 * 1024 * 1024));
        }
    }.file;
    const source = try read(arena, io, args[1]);
    const recorder = try read(arena, io, args[2]);
    const overlay = try read(arena, io, args[3]);
    const rrweb = try read(arena, io, args[4]);
    var out = try cwd.openDir(io, args[5], .{});
    defer out.close(io);

    // rrweb's recorder, shielded from AMD/CommonJS loaders on the host page so
    // it always lands on window, then the Analytico glue.
    const replay = try std.mem.concat(arena, u8, &.{ "(function (define, module, exports) {\n", rrweb, "\n}).call(window);\n", recorder });
    try out.writeFile(io, .{ .sub_path = "replay.js", .data = replay });
    try out.writeFile(io, .{ .sub_path = "overlay.js", .data = overlay });
    const replay_path = try std.fmt.allocPrint(arena, "/t/replay.{s}.js", .{shortHash(replay)});
    const overlay_path = try std.fmt.allocPrint(arena, "/t/overlay.{s}.js", .{shortHash(overlay)});

    const Mode = enum { lite, session, full };
    for ([_]struct { []const u8, Mode, bool }{
        .{ "tracker-lite.js", .lite, false },
        .{ "tracker-lite-rum.js", .lite, true },
        .{ "tracker-session.js", .session, false },
        .{ "tracker-session-rum.js", .session, true },
        .{ "tracker-full.js", .full, false },
        .{ "tracker-full-rum.js", .full, true },
    }) |variant| {
        const mode = variant[1];
        const rum = variant[2];
        const replacements = [_][2][]const u8{
            .{ "__MODE__", @tagName(mode) },
            .{ "__SESSION_ID__", if (mode == .session) "loadSession()" else "null" },
            .{ "__REPLAY_PATH__", replay_path },
            .{ "__OVERLAY_PATH__", overlay_path },
        };
        var result: std.ArrayList(u8) = .empty;
        var in_session = false;
        var in_session_only = false;
        var in_full = false;
        var in_rum = false;
        var lines = std.mem.splitScalar(u8, source, '\n');
        while (lines.next()) |line| {
            if (lines.peek() == null and line.len == 0) break;
            if (marker(line, "@session-begin")) {
                in_session = true;
                continue;
            }
            if (marker(line, "@session-end")) {
                in_session = false;
                continue;
            }
            if (marker(line, "@sessiononly-begin")) {
                in_session_only = true;
                continue;
            }
            if (marker(line, "@sessiononly-end")) {
                in_session_only = false;
                continue;
            }
            if (marker(line, "@full-begin")) {
                in_full = true;
                continue;
            }
            if (marker(line, "@full-end")) {
                in_full = false;
                continue;
            }
            if (marker(line, "@rum-begin")) {
                in_rum = true;
                continue;
            }
            if (marker(line, "@rum-end")) {
                in_rum = false;
                continue;
            }
            if (in_session and mode == .lite) continue;
            if (in_session_only and mode != .session) continue;
            if (in_full and mode != .full) continue;
            if (in_rum and !rum) continue;
            // Like sed's s///: the first occurrence on each line.
            var text: []const u8 = line;
            for (replacements) |pair| if (std.mem.find(u8, text, pair[0])) |at| {
                text = try std.mem.concat(arena, u8, &.{ text[0..at], pair[1], text[at + pair[0].len ..] });
            };
            try result.appendSlice(arena, text);
            try result.append(arena, '\n');
        }
        try out.writeFile(io, .{ .sub_path = variant[0], .data = result.items });
    }

    // Content hashes, so served paths are constants and nothing is hashed at runtime.
    var hashes: std.ArrayList(u8) = .empty;
    try hashes.appendSlice(arena, "// Generated by tools/gen_trackers.zig.\n");
    for ([_][]const u8{ "tracker-lite.js", "tracker-lite-rum.js", "tracker-session.js", "tracker-session-rum.js", "tracker-full.js", "tracker-full-rum.js", "replay.js", "overlay.js" }) |name| {
        const bytes = try out.readFileAlloc(io, name, arena, .limited(4 * 1024 * 1024));
        const identifier = try std.mem.replaceOwned(u8, arena, name[0 .. name.len - 3], "-", "_");
        try hashes.print(arena, "pub const {s} = \"{s}\";\n", .{ identifier, shortHash(bytes) });
    }
    try out.writeFile(io, .{ .sub_path = "hashes.zig", .data = hashes.items });
}

fn marker(line: []const u8, name: []const u8) bool {
    var buffer: [40]u8 = undefined;
    const needle = std.fmt.bufPrint(&buffer, "/* {s} */", .{name}) catch return false;
    return std.mem.find(u8, line, needle) != null;
}

/// The first 12 hex digits of SHA-256, as served under /t/.
fn shortHash(bytes: []const u8) [12]u8 {
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
    return std.fmt.bytesToHex(digest[0..6].*, .lower);
}
